apiVersion: v1
kind: Service
metadata:
  name: order-service
spec:
  selector:
    app: order-service
  ports:
    - port: 8080
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
        - name: order-service
          image: samou4ka/order-service:0.1.0
          ports:
            - containerPort: 8080
          env:
            - name: QUARKUS_REST_CLIENT_USER_API_URL
              value: http://user-service:8080
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: my-cluster-kafka-bootstrap.kafka:9092
            - name: QUARKUS_OIDC_AUTH_SERVER_URL
              value: http://keycloak.keycloak.svc.cluster.local/realms/quarkus-realm
